<?php

namespace Records\Orm\QueryHelper;

/**
 * @method \Records\Orm\RecordsQuery equals($value)
 * @method \Records\Orm\RecordsQuery notEquals($value)
 * @method \Records\Orm\RecordsQuery greater($value)
 * @method \Records\Orm\RecordsQuery less($value)
 * @method \Records\Orm\RecordsQuery greaterOrEquals($value)
 * @method \Records\Orm\RecordsQuery lessOrEquals($value)
 * @method \Records\Orm\RecordsQuery like($value)
 * @method \Records\Orm\RecordsQuery ilike($value)
 * @method \Records\Orm\RecordsQuery between($from, $to)
 * @method \Records\Orm\RecordsQuery equalsColumnId()
 * @method \Records\Orm\RecordsQuery notEqualsColumnId()
 * @method \Records\Orm\RecordsQuery greaterThanColumnId()
 * @method \Records\Orm\RecordsQuery lessThanColumnId()
 * @method \Records\Orm\RecordsQuery greaterOrEqualsColumnId()
 * @method \Records\Orm\RecordsQuery lessOrEqualsColumnId()
 * @method \Records\Orm\RecordsQuery equalsColumnImei()
 * @method \Records\Orm\RecordsQuery notEqualsColumnImei()
 * @method \Records\Orm\RecordsQuery greaterThanColumnImei()
 * @method \Records\Orm\RecordsQuery lessThanColumnImei()
 * @method \Records\Orm\RecordsQuery greaterOrEqualsColumnImei()
 * @method \Records\Orm\RecordsQuery lessOrEqualsColumnImei()
 * @method \Records\Orm\RecordsQuery equalsColumnTimestamp()
 * @method \Records\Orm\RecordsQuery notEqualsColumnTimestamp()
 * @method \Records\Orm\RecordsQuery greaterThanColumnTimestamp()
 * @method \Records\Orm\RecordsQuery lessThanColumnTimestamp()
 * @method \Records\Orm\RecordsQuery greaterOrEqualsColumnTimestamp()
 * @method \Records\Orm\RecordsQuery lessOrEqualsColumnTimestamp()
 * @method \Records\Orm\RecordsQuery equalsColumnLatitude()
 * @method \Records\Orm\RecordsQuery notEqualsColumnLatitude()
 * @method \Records\Orm\RecordsQuery greaterThanColumnLatitude()
 * @method \Records\Orm\RecordsQuery lessThanColumnLatitude()
 * @method \Records\Orm\RecordsQuery greaterOrEqualsColumnLatitude()
 * @method \Records\Orm\RecordsQuery lessOrEqualsColumnLatitude()
 * @method \Records\Orm\RecordsQuery equalsColumnLongitude()
 * @method \Records\Orm\RecordsQuery notEqualsColumnLongitude()
 * @method \Records\Orm\RecordsQuery greaterThanColumnLongitude()
 * @method \Records\Orm\RecordsQuery lessThanColumnLongitude()
 * @method \Records\Orm\RecordsQuery greaterOrEqualsColumnLongitude()
 * @method \Records\Orm\RecordsQuery lessOrEqualsColumnLongitude()
 * @method \Records\Orm\RecordsQuery equalsColumnAltitude()
 * @method \Records\Orm\RecordsQuery notEqualsColumnAltitude()
 * @method \Records\Orm\RecordsQuery greaterThanColumnAltitude()
 * @method \Records\Orm\RecordsQuery lessThanColumnAltitude()
 * @method \Records\Orm\RecordsQuery greaterOrEqualsColumnAltitude()
 * @method \Records\Orm\RecordsQuery lessOrEqualsColumnAltitude()
 * @method \Records\Orm\RecordsQuery equalsColumnAngle()
 * @method \Records\Orm\RecordsQuery notEqualsColumnAngle()
 * @method \Records\Orm\RecordsQuery greaterThanColumnAngle()
 * @method \Records\Orm\RecordsQuery lessThanColumnAngle()
 * @method \Records\Orm\RecordsQuery greaterOrEqualsColumnAngle()
 * @method \Records\Orm\RecordsQuery lessOrEqualsColumnAngle()
 * @method \Records\Orm\RecordsQuery equalsColumnSatellites()
 * @method \Records\Orm\RecordsQuery notEqualsColumnSatellites()
 * @method \Records\Orm\RecordsQuery greaterThanColumnSatellites()
 * @method \Records\Orm\RecordsQuery lessThanColumnSatellites()
 * @method \Records\Orm\RecordsQuery greaterOrEqualsColumnSatellites()
 * @method \Records\Orm\RecordsQuery lessOrEqualsColumnSatellites()
 * @method \Records\Orm\RecordsQuery equalsColumnSpeed()
 * @method \Records\Orm\RecordsQuery notEqualsColumnSpeed()
 * @method \Records\Orm\RecordsQuery greaterThanColumnSpeed()
 * @method \Records\Orm\RecordsQuery lessThanColumnSpeed()
 * @method \Records\Orm\RecordsQuery greaterOrEqualsColumnSpeed()
 * @method \Records\Orm\RecordsQuery lessOrEqualsColumnSpeed()
 */
class RecordsQueryField extends \Mmi\Orm\QueryHelper\QueryField
{

}
